app/graphical_object/models.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from sqlalchemy.sql import func
from sqlalchemy import  Column, Integer, String, Float, DateTime, ForeignKey

from app import db
from sqlalchemy.orm import relationship
    
class Document(db.Model):
    __tablename__ = 'Documents'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    total_page = Column(Integer)
    annotations = Column(String)
    createdOn = Column(DateTime(timezone=True), default=func.now())
    createdBy = Column(String)

app/graphical_object/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'graphical_object_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static',
    static_url_path = ""
)

app/graphical_object/routes.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from app.graphical_object import blueprint
from flask import render_template, redirect, url_for
from flask_login import login_required, current_user
from app import login_manager
from jinja2 import TemplateNotFound
from app import db
from sqlalchemy import desc, asc
from flask import request
import json
from sqlalchemy.sql import func
from werkzeug.utils import secure_filename
import os
from app.graphical_object.utils import convert_hash
from app.graphical_object.utils import hamming
from app.graphical_object.utils import dhash
from imutils import paths
from imutils import url_to_image
import pickle
import vptree
import cv2
import time
from zipfile import ZipFile
import io


basedir = os.path.abspath(os.path.dirname(__file__))
result = {'query':'web/E2.png'}
detect = []
@blueprint.route('/graphical_object/indexing')
@login_required
def indexing():
    # check exist user
    if not current_user.is_authenticated:
        return redirect(url_for('base_blueprint.login'))
    return render_template('indexing.html')

@blueprint.route('/graphical_object/index_images', methods=['POST'])
@login_required
def index_images():
    try:
        basedir = os.path.abspath(os.path.dirname(__file__))
        # load the input query image
        file =  request.files.to_dict()
        # Store Pdf with convert_from_path function
        filename = secure_filename(file['file'].filename)
        upload_path = os.path.join(basedir, 'static', 'images')
        # specifying the zip file name
        file_path = os.path.join(upload_path, filename)
        #file['file'].save(file_path)
        z = ZipFile(file['file'].stream._file)

        print('Extracting all the files now...')
        z.extractall(upload_path)
        print('Done!')

        # # delete the zip file
        # os.remove(file_path)

        # grab the paths to the input images and initialize the dictionary
        # of hashes

        imagePaths = list(paths.list_images(os.path.join(basedir, 'static','images')))
        hashes = {}
        print(imagePaths)
        # loop over the image paths
        for (i, imagePath) in enumerate(imagePaths):
	        # load the input image
	        print("[INFO] processing image {}/{}".format(i + 1, len(imagePaths)))
	        image = cv2.imread(imagePath)
	        # compute the hash for the image and convert it
	        h = dhash(image)
	        h = convert_hash(h)
	        # update the hashes dictionary
	        l = hashes.get(h, [])
	        l.append(imagePath)
	        hashes[h] = l

        # build the VP-Tree
        print("[INFO] building VP-Tree...")
        points = list(hashes.keys())
        tree = vptree.VPTree(points, hamming)

        # serialize the VP-Tree to disk
        print("[INFO] serializing VP-Tree...")
        tree_path = os.path.join(basedir, 'static','indexing','vptree.pickle')
        f = open(tree_path, "wb")
        f.write(pickle.dumps(tree))
        f.close()
        # serialize the hashes to dictionary
        print("[INFO] serializing hashes...")
        hash_path = os.path.join(basedir, 'static','indexing','hashes.pickle')
        f = open(hash_path, "wb")
        f.write(pickle.dumps(hashes))
        f.close()

        return json.dumps({'status': 'OK','message':'The Result of the indexing is saved!{}'.format(file_path)})
    except:
        return json.dumps({'status': 'OK','message':'Error in the processing of the indexing. Please try again!'})

@blueprint.route('/graphical_object/searching')
@login_required
def searching():
    # check exist user
    if not current_user.is_authenticated:
        return redirect(url_for('base_blueprint.login'))
    return render_template('searching.html', result = result)

@blueprint.route('/graphical_object/search', methods=['POST'])
@login_required
def search():
    # load the VP-Tree and hashes dictionary
    print("[INFO] loading VP-Tree and hashes...")
    tree_path = os.path.join(basedir, 'static','indexing','vptree.pickle')
    tree = pickle.loads(open(tree_path, "rb").read())

    hash_path = os.path.join(basedir, 'static','indexing','hashes.pickle')
    hashes = pickle.loads(open(hash_path, "rb").read())

    # load the input query image
    form = request.form.to_dict()
    file = request.files.to_dict()

    if form['link'] == '':
        filename = secure_filename(file['file'].filename)
        image_query = os.path.join(basedir, 'static', 'queries', filename)
        file['file'].save(image_query)
        query = '/queries/{}'.format(filename)
        image = cv2.imread(image_query)
    else:
        image_query = form['link']
        image = url_to_image(image_query)

    # compute the hash for the query image, then convert it
    queryHash = dhash(image)
    queryHash = convert_hash(queryHash)

    # perform the search
    print("[INFO] performing search...")
    start = time.time()
    results = tree.get_all_in_range(queryHash, 20)
    results = sorted(results)
    end = time.time()
    print("[INFO] search took {} seconds".format(end - start))
    response = []
    # loop over the results
    for (d, h) in results:
	    # grab all image paths in our dataset with the same hash
        paths = ['/' + '/'.join(path.split('\\')[5:]) for path in hashes.get(h, [])]

        r = {'score' : (20-d)*5 , 'hash': h, 'paths': paths }
	    # print("[INFO] {} total image(s) with d: {}, h: {}".format(
		#     len(resultPaths), d, h))
	    # print(resultPaths)
        response.append(r)

    #res = json.dumps({'status': 'OK','message':'The Result of the search is displayed!', 'response' : response}, ensure_ascii=False)

    global result
    result = {'response': response, 'time': round(end - start, 5), 'query': query}
    return json.dumps({'status': 'OK','message':'The Result of the search is displayed!'})

@blueprint.route('/graphical_object/detect', methods=['POST'])
@login_required
def detect():
    # check exist user
    if not current_user.is_authenticated:
        return redirect(url_for('base_blueprint.login'))

    return json.dumps({'status': 'OK','message':'The Result of the detection is displayed!'})

@blueprint.route('/graphical_object/detection')
@login_required
def detection():
    # check exist user
    if not current_user.is_authenticated:
        return redirect(url_for('base_blueprint.login'))

    return render_template('detection.html', detect = detect)

@blueprint.route('graphical_object/<template>')
def route_template(template):

    if not current_user.is_authenticated:
        return redirect(url_for('base_blueprint.login'))

    try:

        return render_template(template + '.html')

    except TemplateNotFound:
        return render_template('page-404.html'), 404

    except:
        return render_template('page-500.html'), 500
@blueprint.route('graphical_object/<static>')
def route_static(static):

    if not current_user.is_authenticated:
        return redirect(url_for('base_blueprint.login'))

    try:

        return render_template(static + '.html')

    except TemplateNotFound:
        return render_template('page-404.html'), 404

    except:
        return render_template('page-500.html'), 500

app/graphical_object/templates/detection.html
{% extends "layouts/base.html" %}

{% block title %} Detection Page{% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} {% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="/static/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %} 

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Detection Page</h1>
            
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Detection</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Detection</h3>
                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                </div>
              </div>
              <form id="form" enctype="multipart/form-data" method="post" >
                <div class="card-body">
                 <div class="row" id="multiple" >
                  <div class="col-sm-2"></div>
                  <div class="col-sm-8">
                    <div class="form-group">
                      <!-- <label for="customFile">Custom File</label> -->
                      <div class="custom-file">
                        <input type="file" name="file" class="custom-file-input" id="customFile">
                        <label class="custom-file-label" for="customFile">Choose a file with pdf extension</label>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-2"></div>
                 </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <div class="row">
                    <div class="col-sm-5"></div>
                    <div class="col-sm-3">
                      <button type="submit"   class="btn btn-primary">Detection</button>
                    </div>
                    <div class="col-sm-4"></div>
                  </div>
                </div>
              </form>
              <div class="overlay dark" id="detect" style="display: none;">
                <i class="fas fa-2x fa-sync-alt fa-spin"></i>
              </div>
            </div>
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
        <div class="row">
          <div class="col-12">
            <p>{{detect}}</p>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- DataTables -->
  <script src="/static/assets/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- bs-custom-file-input -->
  <script src="/static/assets/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
  <!-- jquery-validation -->
  <script src="/static/assets/plugins/jquery-validation/jquery.validate.min.js"></script>
  <script src="/static/assets/plugins/jquery-validation/additional-methods.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>
  <!-- page script -->
  <script>
    $(function () {
    $('#form').validate({
      rules: {
        file: {
          required: true,
          extension: "pdf"
        }
      },
      submitHandler: function (form) {
        
              var formData = new FormData($('#form').get(0));

              $('#detect').css("display", "");

             $.ajax({
                url: "{{ url_for('graphical_object_blueprint.detect') }}",
                data:  formData,
                method: "POST",
                mimeType: "multipart/form-data",
                //Options to tell jQuery not to process data or worry about content-type.
                cache: false,
                contentType: false,
                processData: false,
                success: function (response) {
                  $('#detect').css("display", "none");
                  alert($.parseJSON(response)['message']);
                },
                error: function (error) {
                $('#detect').css("display", "none");
                alert($.parseJSON(error));
                }
             });
             return false; // required to block normal submit since you used ajax
         },
      messages: {
        file: {
          required: "Please choose a file",
          extension: "Please choose a file with a valid extension."
        }
      },
      errorElement: 'span',
      errorPlacement: function (error, element) {
        error.addClass('invalid-feedback');
        element.closest('.form-group').append(error);
      },
      highlight: function (element, errorClass, validClass) {
        $(element).addClass('is-invalid');
      },
      unhighlight: function (element, errorClass, validClass) {
        $(element).removeClass('is-invalid');
      }
    });
  });
 
  </script>

{% endblock javascripts %}

app/graphical_object/templates/searching.html
{% extends "layouts/base.html" %}

{% block title %} Searching Page{% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} {% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="/static/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %} 

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Searching</h1>
            
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Image search</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Live search</h3>
                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                </div>
              </div>
              <form id="form" enctype="multipart/form-data" method="post" action="{{ url_for('graphical_object_blueprint.search') }}" >
                <div class="card-body">
                  <div class="row">
                    <div class="col-3"></div>
                    <div class="col-sm-2">
                      <p style="margin-top: 5%; margin-bottom: 1rem; padding-left: 45%;"><span style="font-size: medium;font-weight: bold;"> Image URL(s)</span></p>
                    </div>
                    <div class="col-sm-4">
                      <div class="btn-group btn-group-toggle" data-toggle="buttons">
                        <label class="btn bg-olive active">
                          <input type="radio" name="options" id="option_b1" autocomplete="off" checked> Url 
                        </label>
                        <label class="btn bg-olive">
                          <input type="radio" name="options" id="option_b2" autocomplete="off"> Upload  
                        </label>
                      </div>
                    </div>
                    <div class="col-sm-3"></div>
                  </div>
                 <div class="row" id="single" style="display: '';" >
                  <div class="col-sm-2"></div>
                  <div class="col-sm-8">
                    <div class="form-group">
                      <!-- <label for="exampleInputEmail1">Image URL</label> -->
                      <input type="text" name="link" class="form-control" id="exampleInputEmail1" placeholder="Enter a URL of the image">
                    </div>
                  </div>
                  <div class="col-sm-2"></div>
                  
                 </div>
                 <div class="row" id="multiple" style="display: none;">
                  <div class="col-sm-2"></div>
                  <div class="col-sm-8">
                    <div class="form-group">
                      <!-- <label for="customFile">Custom File</label> -->
                      <div class="custom-file">
                        <input type="file" name="file" class="custom-file-input" id="customFile">
                        <label class="custom-file-label" for="customFile">Choose a image with jpg|png|jpeg extension</label>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-2"></div>
                 </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <div class="row">
                    <div class="col-sm-5"></div>
                    <div class="col-sm-3">
                      <button type="submit"   class="btn btn-primary">Search for image</button>
                    </div>
                    <div class="col-sm-4"></div>
                  </div>
                </div>
              </form>
              <div class="overlay dark" id="load_search" style="display: none;">
                <i class="fas fa-2x fa-sync-alt fa-spin"></i>
              </div>
            </div>
            
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Result for search</h3>
                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                </div>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-1"></div>
                  <div class="col-4">
                    <div class="card">
                      <div class="card-header">
                        <h5 class="card-title">Input</h5>
                      </div>
                      <div class="card-body">
                        <img src="{{url_for('graphical_object_blueprint.static', filename=result['query'])}}"
                        style="width: 300px;height: 300px;" />
                      </div>
                    </div>
                 </div>
                 <div class="col-2"> 
                 </div>
                 <div class="col-4">
                  <div class="card">
                    <div class="card-header">
                      <h5 class="card-title">Output</h5>
                    </div>
                    <div class="card-body" style="MAX-HEIGHT: 600PX;
                    overflow-y: auto;">
                      <div class="row">
                        <p>Time: {{result['time']}}&nbsp;seconds</p>
                      </div>
                      {% if result['response'] == [] %}
                      <div class="row">
                      <p>Not found relatave images!</p>
                      </div>
                      {% endif %}
                      {% for res in result['response'] %}
                      <div class="row">
                        <p>Score: {{res['score']}}%</p>
                        <img src="{{res['paths'][0]}}" style="width: 300px;height: 300px;" />
                      </div>
                      {% endfor %}
                    </div>
                    </div>
                  </div>
                   
                 <div class="col-1"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- DataTables -->
  <script src="/static/assets/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- bs-custom-file-input -->
  <script src="/static/assets/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
  <!-- jquery-validation -->
  <script src="/static/assets/plugins/jquery-validation/jquery.validate.min.js"></script>
  <script src="/static/assets/plugins/jquery-validation/additional-methods.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>
  <!-- page script -->
  <script>
    $(function () {
    $('#form').validate({
      rules: {
        link: {
          required: true,
          url: true,
          extension: "jpg,jpeg,png"
        },
        image: {
          required: true,
          extension: "jpg,jpeg,pn"
        }
      },
      submitHandler: function (form) {
        
              var formData = new FormData($('#form').get(0));

              $('#load_search').css("display", "");

             $.ajax({
                url: "{{ url_for('graphical_object_blueprint.search') }}",
                data:  formData,
                method: "POST",
                mimeType: "multipart/form-data",
                //Options to tell jQuery not to process data or worry about content-type.
                cache: false,
                contentType: false,
                processData: false,
                success: function (response) {
                  $('#load_search').css("display", "none");
                  alert($.parseJSON(response)['message']);
                  location.replace("{{ url_for('graphical_object_blueprint.searching')}}");
                },
                error: function (error) {
                $('#load_search').css("display", "none");
                alert($.parseJSON(error));
                location.replace("{{ url_for('graphical_object_blueprint.searching')}}");
                }
             });
             return false; // required to block normal submit since you used ajax
         },
      messages: {
        link: {
          required: "Please enter a url",
          url: "Please enter a vaild url",
          extension: "Please enter a valid url of the image"
        },
        image: {
          required: "Please choose a file",
          extension: "Please choose a file with a valid extension."
        }
      },
      errorElement: 'span',
      errorPlacement: function (error, element) {
        error.addClass('invalid-feedback');
        element.closest('.form-group').append(error);
      },
      highlight: function (element, errorClass, validClass) {
        $(element).addClass('is-invalid');
      },
      unhighlight: function (element, errorClass, validClass) {
        $(element).removeClass('is-invalid');
      }
    });
  });
  $(function(){
    // Set div display to none
    $("#option_b2").click(function(){
        $("#single").css("display", "none");
        $("#multiple").css("display", "");
    });
    
    // Set div display to block
    $("#option_b1").click(function(){
      $("#single").css("display", "");
        $("#multiple").css("display", "none");
    });
  });
  </script>

{% endblock javascripts %}